# -*- coding: utf-8 -*-
print("Hello, this is a Python script.")
print("Hook['params'] is populated with request parameters")
print(Hook['params'])
print("Hook['req'] is the http request")
print(Hook['req']['url'])
print(u"проверка кодировки")
print(u"סיסטעם פּרובירן")
print(u"編碼測試")
print(u"エンコードテスト")
print(u"एन्कोडिंग परीक्षण")
